export type User = {
  id: string;
  name: string;
  email: string;
  role: string;
};

export async function getUsers(): Promise<User[]> {
  return [
    {
      id: "1",
      name: "Medio Prado",
      email: "medio.prado@example.com",
      role: "Admin",
    },
    {
      id: "2",
      name: "Roger Vera",
      email: "roger.vera@example.com",
      role: "User",
    },
    {
      id: "3",
      name: "Alejandro Loaiza",
      email: "alejandro.loaiza@example.com",
      role: "User",
    },
    {
      id: "4",
      name: "Costeño hijodeputa",
      email: "costeño.hijodeputa@example.com",
      role: "User",
    },
    {
      id: "5",
      name: "Lucho abejorral",
      email: "lucho.abejorral@example.com",
      role: "User",
    },
    {
      id: "6",
      name: "Juan Pablo",
      email: "juan.pablo@example.com",
      role: "User",
    },
    {
      id: "7",
      name: "Test",
      email: "test@example.com",
      role: "User",
    },
    {
      id: "8",
      name: "Tomas Gonzalez",
      email: "tomas.gonzalez@example.com",
      role: "User",
    },
    {
      id: "9",
      name: "Jorge Lopez",
      email: "jorge.lopez@example.com",
      role: "User",
    },
    {
      id: "10",
      name: "Pedro Perez",
      email: "pedro.perez@example.com",
      role: "User",
    },
    {
      id: "11",
      name: "Juan Perez",
      email: "juan.perez@example.com",
      role: "User",
    },
    {
      id: "12",
      name: "John Smith",
      email: "john.smith@example.com",
      role: "User",
    },
    {
      id: "13",
      name: "Jane Doe",
      email: "jane.doe@example.com",
      role: "User",
    },
    {
      id: "14",
      name: "John Doe",
      email: "john.doe@example.com",
      role: "User",
    },
    {
      id: "15",
      name: "Ana Martínez",
      email: "ana.martinez@example.com",
      role: "User",
    },
    {
      id: "16",
      name: "Carlos Núñez",
      email: "carlos.nunez@example.com",
      role: "User",
    },
    {
      id: "17",
      name: "Lucía Fernández",
      email: "lucia.fernandez@example.com",
      role: "Editor",
    },
    {
      id: "18",
      name: "Miguel Torres",
      email: "miguel.torres@example.com",
      role: "User",
    },
    {
      id: "19",
      name: "Sofía Ramírez",
      email: "sofia.ramirez@example.com",
      role: "User",
    },
    {
      id: "20",
      name: "Andrés Castillo",
      email: "andres.castillo@example.com",
      role: "Admin",
    },
    {
      id: "21",
      name: "Valentina Rojas",
      email: "valentina.rojas@example.com",
      role: "User",
    },
    {
      id: "22",
      name: "Diego Hernández",
      email: "diego.hernandez@example.com",
      role: "User",
    },
    {
      id: "23",
      name: "Camila Vargas",
      email: "camila.vargas@example.com",
      role: "User",
    },
    {
      id: "24",
      name: "Felipe Navarro",
      email: "felipe.navarro@example.com",
      role: "Viewer",
    },
    {
      id: "25",
      name: "Laura Mejía",
      email: "laura.mejia@example.com",
      role: "User",
    },
    {
      id: "26",
      name: "Daniela Pineda",
      email: "daniela.pineda@example.com",
      role: "Editor",
    },
    {
      id: "27",
      name: "Sebastián Salazar",
      email: "sebastian.salazar@example.com",
      role: "User",
    },
    {
      id: "28",
      name: "Paula Quintero",
      email: "paula.quintero@example.com",
      role: "User",
    },
    {
      id: "29",
      name: "Mateo Álvarez",
      email: "mateo.alvarez@example.com",
      role: "Viewer",
    },
    {
      id: "30",
      name: "Juliana Díaz",
      email: "juliana.diaz@example.com",
      role: "User",
    },
    {
      id: "31",
      name: "Tomás Herrera",
      email: "tomas.herrera@example.com",
      role: "User",
    },
    {
      id: "32",
      name: "Gabriela Campos",
      email: "gabriela.campos@example.com",
      role: "User",
    },
    {
      id: "33",
      name: "Emilio Santana",
      email: "emilio.santana@example.com",
      role: "Editor",
    },
    {
      id: "34",
      name: "Isabella Cárdenas",
      email: "isabella.cardenas@example.com",
      role: "User",
    },
    {
      id: "35",
      name: "Santiago Márquez",
      email: "santiago.marquez@example.com",
      role: "User",
    },
    {
      id: "36",
      name: "Renata Gil",
      email: "renata.gil@example.com",
      role: "Viewer",
    },
    {
      id: "37",
      name: "Agustín Lara",
      email: "agustin.lara@example.com",
      role: "User",
    },
    {
      id: "38",
      name: "Mariana Pardo",
      email: "mariana.pardo@example.com",
      role: "User",
    },
    {
      id: "39",
      name: "Alejo Gómez",
      email: "alejo.gomez@example.com",
      role: "User",
    },
    {
      id: "40",
      name: "Nicole Duarte",
      email: "nicole.duarte@example.com",
      role: "Editor",
    },
    {
      id: "41",
      name: "Pablo Medina",
      email: "pablo.medina@example.com",
      role: "User",
    },
    {
      id: "42",
      name: "Carolina Rincón",
      email: "carolina.rincon@example.com",
      role: "User",
    },
    {
      id: "43",
      name: "Álvaro León",
      email: "alvaro.leon@example.com",
      role: "Viewer",
    },
    {
      id: "44",
      name: "Elena Vargas",
      email: "elena.vargas@example.com",
      role: "User",
    },
    {
      id: "45",
      name: "Rafael Castro",
      email: "rafael.castro@example.com",
      role: "User",
    },
    {
      id: "46",
      name: "Victoria Mora",
      email: "victoria.mora@example.com",
      role: "Admin",
    },
    {
      id: "47",
      name: "Martín Peña",
      email: "martin.pena@example.com",
      role: "User",
    },
    {
      id: "48",
      name: "Daniel Rivas",
      email: "daniel.rivas@example.com",
      role: "User",
    },
    {
      id: "49",
      name: "Antonia Suárez",
      email: "antonia.suarez@example.com",
      role: "User",
    },
    {
      id: "50",
      name: "Bruno Gómez",
      email: "bruno.gomez@example.com",
      role: "Viewer",
    },
    {
      id: "51",
      name: "Sara Del Valle",
      email: "sara.delvalle@example.com",
      role: "User",
    },
    {
      id: "52",
      name: "Ignacio Vera",
      email: "ignacio.vera@example.com",
      role: "User",
    },
    {
      id: "53",
      name: "Camilo Ortega",
      email: "camilo.ortega@example.com",
      role: "Editor",
    },
    {
      id: "54",
      name: "Luisa Castaño",
      email: "luisa.castano@example.com",
      role: "User",
    },
  ];
}
