export type User = EquipmentInsight;

export async function getUsers(): Promise<User[]> {
  return getEquipmentInsights();
}

// Nuevos tipos y datos para Equipment Insights
export type EquipmentInsight = {
  nombre?: string | null;
  cedula_empleado?: number | null;
  service_req_number?: number | null;
  tipo_de_contrato?: string | null;
  estado_del_caso?: string | null;
  fecha_transferencia?: string | null; // ISO string (YYYY-MM-DD)
  fecha_programacion?: string | null; // ISO string (YYYY-MM-DD)
  fecha_creacion?: string | null; // ISO string (YYYY-MM-DD)
  fecha_cierre?: string | null; // ISO string (YYYY-MM-DD)
  fecha_ingreso_usuario?: string | null; // ISO string (YYYY-MM-DD)
  dias_ingreso_vs_sln?: number | null;
  ano_caso?: number | null;
  mes_caso?: string | null;
  semana_caso?: string | null;
  ano_sln?: number | null;
  mes_sln?: string | null;
  semana_sln?: string | null;
  mes_ingreso?: string | null;
  dia_ingreso?: number | null;
  ano?: number | null;
  ans_entrega?: string | null;
  dias_entrega?: number | null;
  dias_ingreso?: number | null;
  ans_ingreso?: string | null;
  kpi?: string | null;
  cumplimiento_kpi?: string | null;
  excepcion?: string | null;
  motivo_excepcion?: string | null;
  observaciones?: string | null;
};

type RawEquipmentInsight = {
  [key: string]: string;
};

const removeNonDigits = (value: string | undefined): string => {
  if (!value) return "";
  return value.replace(/[^0-9]/g, "");
};

const toNumberOrNull = (value: string | undefined): number | null => {
  if (!value) return null;
  const cleaned = removeNonDigits(value);
  if (!cleaned) return null;
  const n = Number(cleaned);
  return Number.isFinite(n) ? n : null;
};

const isPlaceholder = (value: string | undefined): boolean => {
  if (!value) return true;
  const v = value.trim();
  return v === "" || v.toUpperCase() === "#NAME?";
};

const toStringOrNull = (value: string | undefined): string | null => {
  if (isPlaceholder(value)) return null;
  return value as string;
};

const toISODateOrNull = (value: string | undefined): string | null => {
  if (isPlaceholder(value)) return null;
  // Espera formato M/D/YYYY o similar. Creamos ISO YYYY-MM-DD de forma segura.
  const parts = (value ?? "").split("/").map((p) => p.trim());
  if (parts.length !== 3) return null;
  const [mStr, dStr, yStr] = parts;
  const year = Number(removeNonDigits(yStr));
  const month = Number(removeNonDigits(mStr));
  const day = Number(removeNonDigits(dStr));
  if (!year || !month || !day) return null;
  const mm = String(month).padStart(2, "0");
  const dd = String(day).padStart(2, "0");
  return `${year}-${mm}-${dd}`;
};

const RAW_EQUIPMENT_INSIGHTS: RawEquipmentInsight[] = [
  {
    Nombre: "Sebastian Espitia Sanchez",
    "Cedula Empleado": "1,006,868,645",
    "Service Req Number": "529,691",
    "Tipo De Contrato": "Vinculado",
    "Estado Del Caso ": "Closed",
    "Fecha transferencia": "4/1/2025",
    "Fecha Programacion": "",
    "Fecha creacion": "4/1/2025",
    "Fecha Resolución": "",
    "Fecha cierre": "4/13/2025",
    "Fecha Ingreso Usuario": "4/7/2025",
    "Días Ingreso vs Sln": "",
    "Año Caso": "2,025",
    "Mes Caso": "April",
    "Semana Caso": "#NAME?",
    "Año Sln": "2,025",
    "Mes Sln": "April",
    "Semana Sln": "#NAME?",
    "Mes Ingreso": "April",
    "Dia ingreso": "7",
    Año: "2,025",
    "Ans Entrega": "#NAME?",
    "Dias Entrega": "#NAME?",
    "Dias Ingreso": "#NAME?",
    "Ans Ingreso": "#NAME?",
    KPI: "80%",
    "Cumplimiento KPI": "#NAME?",
    Excepción: "",
    "Motivo Excepción": "",
    Observaciones: "",
  },
  {
    Nombre: "Carolina Acevedo Colorado",
    "Cedula Empleado": "1,216,725,093",
    "Service Req Number": "530,501",
    "Tipo De Contrato": "Aprendizaje",
    "Estado Del Caso ": "Closed",
    "Fecha transferencia": "4/7/2025",
    "Fecha Programacion": "",
    "Fecha creacion": "4/2/2025",
    "Fecha Resolución": "",
    "Fecha cierre": "4/14/2025",
    "Fecha Ingreso Usuario": "4/2/2025",
    "Días Ingreso vs Sln": "",
    "Año Caso": "2,025",
    "Mes Caso": "April",
    "Semana Caso": "#NAME?",
    "Año Sln": "2,025",
    "Mes Sln": "April",
    "Semana Sln": "#NAME?",
    "Mes Ingreso": "April",
    "Dia ingreso": "2",
    Año: "2,025",
    "Ans Entrega": "#NAME?",
    "Dias Entrega": "#NAME?",
    "Dias Ingreso": "#NAME?",
    "Ans Ingreso": "#NAME?",
    KPI: "80%",
    "Cumplimiento KPI": "#NAME?",
    Excepción: "",
    "Motivo Excepción": "",
    Observaciones: "",
  },
  {
    Nombre: "Natasha Ospina Arrubla",
    "Cedula Empleado": "1,036,654,769",
    "Service Req Number": "531,242",
    "Tipo De Contrato": "Vinculado",
    "Estado Del Caso ": "Closed",
    "Fecha transferencia": "4/3/2025",
    "Fecha Programacion": "",
    "Fecha creacion": "4/3/2025",
    "Fecha Resolución": "",
    "Fecha cierre": "4/13/2025",
    "Fecha Ingreso Usuario": "4/4/2025",
    "Días Ingreso vs Sln": "",
    "Año Caso": "2,025",
    "Mes Caso": "April",
    "Semana Caso": "#NAME?",
    "Año Sln": "2,025",
    "Mes Sln": "April",
    "Semana Sln": "#NAME?",
    "Mes Ingreso": "April",
    "Dia ingreso": "4",
    Año: "2,025",
    "Ans Entrega": "#NAME?",
    "Dias Entrega": "#NAME?",
    "Dias Ingreso": "#NAME?",
    "Ans Ingreso": "#NAME?",
    KPI: "80%",
    "Cumplimiento KPI": "#NAME?",
    Excepción: "",
    "Motivo Excepción": "",
    Observaciones: "",
  },
  {
    Nombre: "Angie Gicela Alvarez Grajales",
    "Cedula Empleado": "1,020,470,272",
    "Service Req Number": "529,685",
    "Tipo De Contrato": "Vinculado",
    "Estado Del Caso ": "Closed",
    "Fecha transferencia": "4/1/2025",
    "Fecha Programacion": "",
    "Fecha creacion": "4/1/2025",
    "Fecha Resolución": "",
    "Fecha cierre": "4/8/2025",
    "Fecha Ingreso Usuario": "4/2/2025",
    "Días Ingreso vs Sln": "",
    "Año Caso": "2,025",
    "Mes Caso": "April",
    "Semana Caso": "#NAME?",
    "Año Sln": "2,025",
    "Mes Sln": "April",
    "Semana Sln": "#NAME?",
    "Mes Ingreso": "April",
    "Dia ingreso": "2",
    Año: "2,025",
    "Ans Entrega": "#NAME?",
    "Dias Entrega": "#NAME?",
    "Dias Ingreso": "#NAME?",
    "Ans Ingreso": "#NAME?",
    KPI: "80%",
    "Cumplimiento KPI": "#NAME?",
    Excepción: "",
    "Motivo Excepción": "",
    Observaciones: "",
  },
  {
    Nombre: "Miguel Angel Cadena Rojas",
    "Cedula Empleado": "1,000,654,169",
    "Service Req Number": "529,518",
    "Tipo De Contrato": "Proveedor",
    "Estado Del Caso ": "Closed",
    "Fecha transferencia": "4/1/2025",
    "Fecha Programacion": "",
    "Fecha creacion": "4/1/2025",
    "Fecha Resolución": "",
    "Fecha cierre": "4/7/2025",
    "Fecha Ingreso Usuario": "3/4/2025",
    "Días Ingreso vs Sln": "",
    "Año Caso": "2,025",
    "Mes Caso": "April",
    "Semana Caso": "#NAME?",
    "Año Sln": "2,025",
    "Mes Sln": "April",
    "Semana Sln": "#NAME?",
    "Mes Ingreso": "March",
    "Dia ingreso": "4",
    Año: "2,025",
    "Ans Entrega": "#NAME?",
    "Dias Entrega": "#NAME?",
    "Dias Ingreso": "#NAME?",
    "Ans Ingreso": "#NAME?",
    KPI: "80%",
    "Cumplimiento KPI": "#NAME?",
    Excepción: "",
    "Motivo Excepción": "",
    Observaciones: "",
  },
  {
    Nombre: "Sebastian Espitia Sanchez",
    "Cedula Empleado": "1,006,868,645",
    "Service Req Number": "529,691",
    "Tipo De Contrato": "Vinculado",
    "Estado Del Caso ": "Closed",
    "Fecha transferencia": "4/1/2025",
    "Fecha Programacion": "",
    "Fecha creacion": "4/1/2025",
    "Fecha Resolución": "",
    "Fecha cierre": "4/13/2025",
    "Fecha Ingreso Usuario": "4/7/2025",
    "Días Ingreso vs Sln": "",
    "Año Caso": "2,025",
    "Mes Caso": "April",
    "Semana Caso": "#NAME?",
    "Año Sln": "2,025",
    "Mes Sln": "April",
    "Semana Sln": "#NAME?",
    "Mes Ingreso": "April",
    "Dia ingreso": "7",
    Año: "2,025",
    "Ans Entrega": "#NAME?",
    "Dias Entrega": "#NAME?",
    "Dias Ingreso": "#NAME?",
    "Ans Ingreso": "#NAME?",
    KPI: "80%",
    "Cumplimiento KPI": "#NAME?",
    Excepción: "",
    "Motivo Excepción": "",
    Observaciones: "",
  },
  {
    Nombre: "Carolina Acevedo Colorado",
    "Cedula Empleado": "1,216,725,093",
    "Service Req Number": "530,501",
    "Tipo De Contrato": "Aprendizaje",
    "Estado Del Caso ": "Closed",
    "Fecha transferencia": "4/7/2025",
    "Fecha Programacion": "",
    "Fecha creacion": "4/2/2025",
    "Fecha Resolución": "",
    "Fecha cierre": "4/14/2025",
    "Fecha Ingreso Usuario": "4/2/2025",
    "Días Ingreso vs Sln": "",
    "Año Caso": "2,025",
    "Mes Caso": "April",
    "Semana Caso": "#NAME?",
    "Año Sln": "2,025",
    "Mes Sln": "April",
    "Semana Sln": "#NAME?",
    "Mes Ingreso": "April",
    "Dia ingreso": "2",
    Año: "2,025",
    "Ans Entrega": "#NAME?",
    "Dias Entrega": "#NAME?",
    "Dias Ingreso": "#NAME?",
    "Ans Ingreso": "#NAME?",
    KPI: "80%",
    "Cumplimiento KPI": "#NAME?",
    Excepción: "",
    "Motivo Excepción": "",
    Observaciones: "",
  },
  {
    Nombre: "Natasha Ospina Arrubla",
    "Cedula Empleado": "1,036,654,769",
    "Service Req Number": "531,242",
    "Tipo De Contrato": "Vinculado",
    "Estado Del Caso ": "Closed",
    "Fecha transferencia": "4/3/2025",
    "Fecha Programacion": "",
    "Fecha creacion": "4/3/2025",
    "Fecha Resolución": "",
    "Fecha cierre": "4/13/2025",
    "Fecha Ingreso Usuario": "4/4/2025",
    "Días Ingreso vs Sln": "",
    "Año Caso": "2,025",
    "Mes Caso": "April",
    "Semana Caso": "#NAME?",
    "Año Sln": "2,025",
    "Mes Sln": "April",
    "Semana Sln": "#NAME?",
    "Mes Ingreso": "April",
    "Dia ingreso": "4",
    Año: "2,025",
    "Ans Entrega": "#NAME?",
    "Dias Entrega": "#NAME?",
    "Dias Ingreso": "#NAME?",
    "Ans Ingreso": "#NAME?",
    KPI: "80%",
    "Cumplimiento KPI": "#NAME?",
    Excepción: "",
    "Motivo Excepción": "",
    Observaciones: "",
  },
  {
    Nombre: "Angie Gicela Alvarez Grajales",
    "Cedula Empleado": "1,020,470,272",
    "Service Req Number": "529,685",
    "Tipo De Contrato": "Vinculado",
    "Estado Del Caso ": "Closed",
    "Fecha transferencia": "4/1/2025",
    "Fecha Programacion": "",
    "Fecha creacion": "4/1/2025",
    "Fecha Resolución": "",
    "Fecha cierre": "4/8/2025",
    "Fecha Ingreso Usuario": "4/2/2025",
    "Días Ingreso vs Sln": "",
    "Año Caso": "2,025",
    "Mes Caso": "April",
    "Semana Caso": "#NAME?",
    "Año Sln": "2,025",
    "Mes Sln": "April",
    "Semana Sln": "#NAME?",
    "Mes Ingreso": "April",
    "Dia ingreso": "2",
    Año: "2,025",
    "Ans Entrega": "#NAME?",
    "Dias Entrega": "#NAME?",
    "Dias Ingreso": "#NAME?",
    "Ans Ingreso": "#NAME?",
    KPI: "80%",
    "Cumplimiento KPI": "#NAME?",
    Excepción: "",
    "Motivo Excepción": "",
    Observaciones: "",
  },
  {
    Nombre: "Miguel Angel Cadena Rojas",
    "Cedula Empleado": "1,000,654,169",
    "Service Req Number": "529,518",
    "Tipo De Contrato": "Proveedor",
    "Estado Del Caso ": "Closed",
    "Fecha transferencia": "4/1/2025",
    "Fecha Programacion": "",
    "Fecha creacion": "4/1/2025",
    "Fecha Resolución": "",
    "Fecha cierre": "4/7/2025",
    "Fecha Ingreso Usuario": "3/4/2025",
    "Días Ingreso vs Sln": "",
    "Año Caso": "2,025",
    "Mes Caso": "April",
    "Semana Caso": "#NAME?",
    "Año Sln": "2,025",
    "Mes Sln": "April",
    "Semana Sln": "#NAME?",
    "Mes Ingreso": "March",
    "Dia ingreso": "4",
    Año: "2,025",
    "Ans Entrega": "#NAME?",
    "Dias Entrega": "#NAME?",
    "Dias Ingreso": "#NAME?",
    "Ans Ingreso": "#NAME?",
    KPI: "80%",
    "Cumplimiento KPI": "#NAME?",
    Excepción: "",
    "Motivo Excepción": "",
    Observaciones: "",
  },
  {
    Nombre: "Sebastian Espitia Sanchez",
    "Cedula Empleado": "1,006,868,645",
    "Service Req Number": "529,691",
    "Tipo De Contrato": "Vinculado",
    "Estado Del Caso ": "Closed",
    "Fecha transferencia": "4/1/2025",
    "Fecha Programacion": "",
    "Fecha creacion": "4/1/2025",
    "Fecha Resolución": "",
    "Fecha cierre": "4/13/2025",
    "Fecha Ingreso Usuario": "4/7/2025",
    "Días Ingreso vs Sln": "",
    "Año Caso": "2,025",
    "Mes Caso": "April",
    "Semana Caso": "#NAME?",
    "Año Sln": "2,025",
    "Mes Sln": "April",
    "Semana Sln": "#NAME?",
    "Mes Ingreso": "April",
    "Dia ingreso": "7",
    Año: "2,025",
    "Ans Entrega": "#NAME?",
    "Dias Entrega": "#NAME?",
    "Dias Ingreso": "#NAME?",
    "Ans Ingreso": "#NAME?",
    KPI: "80%",
    "Cumplimiento KPI": "#NAME?",
    Excepción: "",
    "Motivo Excepción": "",
    Observaciones: "",
  },
  {
    Nombre: "Carolina Acevedo Colorado",
    "Cedula Empleado": "1,216,725,093",
    "Service Req Number": "530,501",
    "Tipo De Contrato": "Aprendizaje",
    "Estado Del Caso ": "Closed",
    "Fecha transferencia": "4/7/2025",
    "Fecha Programacion": "",
    "Fecha creacion": "4/2/2025",
    "Fecha Resolución": "",
    "Fecha cierre": "4/14/2025",
    "Fecha Ingreso Usuario": "4/2/2025",
    "Días Ingreso vs Sln": "",
    "Año Caso": "2,025",
    "Mes Caso": "April",
    "Semana Caso": "#NAME?",
    "Año Sln": "2,025",
    "Mes Sln": "April",
    "Semana Sln": "#NAME?",
    "Mes Ingreso": "April",
    "Dia ingreso": "2",
    Año: "2,025",
    "Ans Entrega": "#NAME?",
    "Dias Entrega": "#NAME?",
    "Dias Ingreso": "#NAME?",
    "Ans Ingreso": "#NAME?",
    KPI: "80%",
    "Cumplimiento KPI": "#NAME?",
    Excepción: "",
    "Motivo Excepción": "",
    Observaciones: "",
  },
  {
    Nombre: "Natasha Ospina Arrubla",
    "Cedula Empleado": "1,036,654,769",
    "Service Req Number": "531,242",
    "Tipo De Contrato": "Vinculado",
    "Estado Del Caso ": "Closed",
    "Fecha transferencia": "4/3/2025",
    "Fecha Programacion": "",
    "Fecha creacion": "4/3/2025",
    "Fecha Resolución": "",
    "Fecha cierre": "4/13/2025",
    "Fecha Ingreso Usuario": "4/4/2025",
    "Días Ingreso vs Sln": "",
    "Año Caso": "2,025",
    "Mes Caso": "April",
    "Semana Caso": "#NAME?",
    "Año Sln": "2,025",
    "Mes Sln": "April",
    "Semana Sln": "#NAME?",
    "Mes Ingreso": "April",
    "Dia ingreso": "4",
    Año: "2,025",
    "Ans Entrega": "#NAME?",
    "Dias Entrega": "#NAME?",
    "Dias Ingreso": "#NAME?",
    "Ans Ingreso": "#NAME?",
    KPI: "80%",
    "Cumplimiento KPI": "#NAME?",
    Excepción: "",
    "Motivo Excepción": "",
    Observaciones: "",
  },
  {
    Nombre: "Angie Gicela Alvarez Grajales",
    "Cedula Empleado": "1,020,470,272",
    "Service Req Number": "529,685",
    "Tipo De Contrato": "Vinculado",
    "Estado Del Caso ": "Closed",
    "Fecha transferencia": "4/1/2025",
    "Fecha Programacion": "",
    "Fecha creacion": "4/1/2025",
    "Fecha Resolución": "",
    "Fecha cierre": "4/8/2025",
    "Fecha Ingreso Usuario": "4/2/2025",
    "Días Ingreso vs Sln": "",
    "Año Caso": "2,025",
    "Mes Caso": "April",
    "Semana Caso": "#NAME?",
    "Año Sln": "2,025",
    "Mes Sln": "April",
    "Semana Sln": "#NAME?",
    "Mes Ingreso": "April",
    "Dia ingreso": "2",
    Año: "2,025",
    "Ans Entrega": "#NAME?",
    "Dias Entrega": "#NAME?",
    "Dias Ingreso": "#NAME?",
    "Ans Ingreso": "#NAME?",
    KPI: "80%",
    "Cumplimiento KPI": "#NAME?",
    Excepción: "",
    "Motivo Excepción": "",
    Observaciones: "",
  },
  {
    Nombre: "Miguel Angel Cadena Rojas",
    "Cedula Empleado": "1,000,654,169",
    "Service Req Number": "529,518",
    "Tipo De Contrato": "Proveedor",
    "Estado Del Caso ": "Closed",
    "Fecha transferencia": "4/1/2025",
    "Fecha Programacion": "",
    "Fecha creacion": "4/1/2025",
    "Fecha Resolución": "",
    "Fecha cierre": "4/7/2025",
    "Fecha Ingreso Usuario": "3/4/2025",
    "Días Ingreso vs Sln": "",
    "Año Caso": "2,025",
    "Mes Caso": "April",
    "Semana Caso": "#NAME?",
    "Año Sln": "2,025",
    "Mes Sln": "April",
    "Semana Sln": "#NAME?",
    "Mes Ingreso": "March",
    "Dia ingreso": "4",
    Año: "2,025",
    "Ans Entrega": "#NAME?",
    "Dias Entrega": "#NAME?",
    "Dias Ingreso": "#NAME?",
    "Ans Ingreso": "#NAME?",
    KPI: "80%",
    "Cumplimiento KPI": "#NAME?",
    Excepción: "",
    "Motivo Excepción": "",
    Observaciones: "",
  },
];

const mapToEquipmentInsight = (raw: RawEquipmentInsight): EquipmentInsight => {
  return {
    nombre: toStringOrNull(raw["Nombre"]),
    cedula_empleado: toNumberOrNull(raw["Cedula Empleado"]),
    service_req_number: toNumberOrNull(raw["Service Req Number"]),
    tipo_de_contrato: toStringOrNull(raw["Tipo De Contrato"]),
    estado_del_caso: toStringOrNull(raw["Estado Del Caso "]),
    fecha_transferencia: toISODateOrNull(raw["Fecha transferencia"]),
    fecha_programacion: toISODateOrNull(raw["Fecha Programacion"]),
    fecha_creacion: toISODateOrNull(raw["Fecha creacion"]),
    fecha_cierre: toISODateOrNull(raw["Fecha cierre"]),
    fecha_ingreso_usuario: toISODateOrNull(raw["Fecha Ingreso Usuario"]),
    dias_ingreso_vs_sln: toNumberOrNull(raw["Días Ingreso vs Sln"]),
    ano_caso: toNumberOrNull(raw["Año Caso"]),
    mes_caso: toStringOrNull(raw["Mes Caso"]),
    semana_caso: toStringOrNull(raw["Semana Caso"]),
    ano_sln: toNumberOrNull(raw["Año Sln"]),
    mes_sln: toStringOrNull(raw["Mes Sln"]),
    semana_sln: toStringOrNull(raw["Semana Sln"]),
    mes_ingreso: toStringOrNull(raw["Mes Ingreso"]),
    dia_ingreso: toNumberOrNull(raw["Dia ingreso"]),
    ano: toNumberOrNull(raw["Año"]),
    ans_entrega: toStringOrNull(raw["Ans Entrega"]),
    dias_entrega: toNumberOrNull(raw["Dias Entrega"]),
    dias_ingreso: toNumberOrNull(raw["Dias Ingreso"]),
    ans_ingreso: toStringOrNull(raw["Ans Ingreso"]),
    kpi: toStringOrNull(raw["KPI"]),
    cumplimiento_kpi: toStringOrNull(raw["Cumplimiento KPI"]),
    excepcion: toStringOrNull(raw["Excepción"]),
    motivo_excepcion: toStringOrNull(raw["Motivo Excepción"]),
    observaciones: toStringOrNull(raw["Observaciones"]),
  };
};

export async function getEquipmentInsights(): Promise<EquipmentInsight[]> {
  return RAW_EQUIPMENT_INSIGHTS.map(mapToEquipmentInsight);
}
